### ISSUE TITLE
arduino.h

### ISSUE THREAD

**Issue by andyrbarrow** [mxtommy/SigkSens#20]
Just doing a test compile with Arduino IDE, and it's failing looking for "arduino.h". Where is that file coming from?

**Comment by mxtommy** [comment]
Hi!

arduino.h should be the main arduino library. It provides base things like Serial.print etc. It's not something specific to SigkSens or any other ESP project. :)

I'll admit to not being the most experienced with Arduino IDE (I set it up once and just left it as is). I think that means though that you did not install the ESP board in the IDE? (I think you need to put a URL for additional boards manager in settings and then go install the board somehow)

If you still can't get it going let me know and I'll see how I can help!

Thomas

**Comment by andyrbarrow** [comment]
Thanks, I'll give it another go. I've got the ESP8266 and ESP32 set up on my Arduino IDE. I was hoping that if I could get it to compile with ESP8266 I'd change the board to ESP32 and see what broke.
The interesting thing was that when I did "sudo locate arduino.h" on my computer I only saw it in a Wifi library. What version of the IDE are you using?

**Comment by andyrbarrow** [comment]
Never mind. I changed the target board to Generic ESP8255 and that particular error disappears. Still not compiling, but at least it's not library issues.

**Comment by andyrbarrow** [comment]
Okay, it compiles for NodeMCU 1.0. I added:
float PI = 3.14159265359f;
#include <math.h>
to the top of quaternionFilters.cpp to get around scope issues.

**Comment by mxtommy** [comment]
:) I'll close this issue, as it's compiling! Let me know how you get on! Would love feedback. If you need anything, I'm usually on the SignalK Dev Slack.
