### ISSUE TITLE
Display data discovered by mDNS, in Serial Monitor

### ISSUE THREAD

**Issue by ba58smith** [mxtommy/SigkSens#35]
The startup process displays data from the config file (hostname, HTTP Port, etc.), and then it runs mDNS. But it doesn't display what mDNS discovered, so you don't know if it discovered anything.
Worse than that, since what it discovered (and is using) isn't displayed in the Serial Monitor, it LOOKS LIKE these bits of data are wrong or missing. Perfect example: I know the Port being used is 3000, because I see that in the SK Dashboard's url, but the only info showing in my SigkSens Serial Monitor says the port is 80.

**Comment by mxtommy** [comment]
Merged :)
