### ISSUE TITLE
Replace all files in Libraries with zip files

### ISSUE THREAD

**Issue by ba58smith** [mxtommy/SigkSens#37]
The Arduino IDE has an easy way to install a Library from a .zip file of that Library - but not a good way to install from a fold that has all the Library's files in it (not that I know of). So if you want to provide an easy way for someone to get to all the Libraries used by SigkSens, simply provide all the zip files. 

(But honestly, if you don't provide any of them, that's probably just fine. They're all documented in Getting_Started.md, including a link to where to find them on GitHub.)

**Comment by mxtommy** [comment]
Done :)

**Comment by ba58smith** [comment]
Thanks! I'll update the Getting Started page in the wiki.
