### ISSUE TITLE
internal LED for LoLin Boards

### ISSUE THREAD

**Issue by hwater** [mxtommy/SigkSens#54]
in "config.h"

//#define LED_BUILTIN 2     // uncommed only for "LoLin" Boards
#define LED_PIN LED_BUILTIN

**Comment by mairas** [comment]
Could you elaborate on this? Would you like to add the commented out section in the code? I'm right now testing with a LoLin board and the `LED_BUILTIN` definition works just fine.

**Comment by mairas** [comment]
No, sorry, you're right, of course. I had the same definition in my local `my_config.h` file. I can add that in a subsequent PR.

**Comment by mxtommy** [comment]
Should be solved by #69 :) Thanks!
