### ISSUE TITLE
FunctionalInterrupt.h

### ISSUE THREAD

**Issue by AliceJ21** [mxtommy/SigkSens#73]
upon compiling, it continually fails with :

FunctionalInterrupt.cpp:1:33: error: FunctionalInterrupt.h: No such file or directory

 #include <FunctionalInterrupt.h>

I have tried manually putting the .cpp and .h files into the sketch but it still comes up with this error.

**Comment by ba58smith** [comment]
AliceJ21, I think I had that problem when I was first trying to compile for an ESP32. It ended up being the wrong version of a library, I think. Be SURE to read the detailed instructions I wrote in the Getting Started document in the wiki.

**Comment by AliceJ21** [comment]
I have managed to crack it - the esp8266 library for Arduino was not installed! Thanks
