### ISSUE TITLE
WilhelmSK

### ISSUE THREAD

**Issue by daverit** [mxtommy/SigkSens#76]
Hi 
I am a real novice and have been trying to get the ESP8266 working with Openplotter and WhilhelmSK. I could get the test sensor data flowing to OP and displayed on the SK Intrument app. I could also see the data on WhilhelmSK but I could not get it to display. I spoke to Scott Bender and he suggested changing the path from sensors.hostname.systemHz to electrical.hostname.systemHz. This fixed the problem. I understand according to him that sensors is reserved for sensor specification and should not be used in a delta path. Interested in your comments and if this change is the correct way to go. Thanks!

**Comment by mxtommy** [comment]
I trust Scott, I updated the default to electrical.hostname.systemHz

Thanks!
