### ISSUE TITLE
Getting Started update: AsyncTCP idf-update tree not available

### ISSUE THREAD

**Issue by bhavers** [mxtommy/SigkSens#81]
Hi, the Getting Started guide says that you should download the "idf-update" branch AyncTCP.
In the latest version that branch does not exist anymore, but the program seems to compile fine with the latest version.

**Comment by ba58smith** [comment]
Next time I'm going to make a change, I'll try the latest version. Thanks for the heads up.

**Comment by andyrbarrow** [comment]
Mine fails on PlatformIO with "fatal: Remote branch idf-update not found in upstream origin". Were you compiling on Arduino IDE or PlatformIO?

**Comment by ba58smith** [comment]
@andyrbarrow, did you try it with the latest version of AsyncTCP? @bhavers says (above) that it worked for him. I've not tested it yet. I use the Arduino IDE, but I'm sure you can tell PlatformIO to use the latest version.

**Comment by bhavers** [comment]
i didn't find a idf-update branch, so used the master branch (on Arduino). Use this link https://github.com/me-no-dev/AsyncTCP/tree/master

**Comment by ba58smith** [comment]
I just downloaded the current AsyncTCP Master and it compiled, and it worked. So I changed the Getting Started Wiki to point to that, and I'm closing this Issue.
