### ISSUE TITLE
How do i turn of the ESP_xxxxxxx wireless network SSID?

### ISSUE THREAD

**Issue by bhavers** [mxtommy/SigkSens#83]
I have configured SigkSens on a (Wemos D1 mini) to connect to the wifi of signalk-server. But even though it is connected it has an SSID of its own network active (ESP_xxxxxx). I can even connect to this and (although inconsistently) it shows a JSON dump of the data.
I would prefer to shut this ESP_xxxx network down. Is that possible?

**Comment by ba58smith** [comment]
Please see https://github.com/mxtommy/SigkSens/issues/80
