### ISSUE TITLE
Using more than one ADS1115

### ISSUE THREAD

**Issue by doccodyblue** [mxtommy/SigkSens#85]
I have a setup with 2 ADS1115, one at 0x48 and one at 0x49. 
By default only the first ADS is detected.For a battery monitor you sometimes will need more than 2 differential ports. (Maybe 3 batteries, currents and a solar)

Is there a way to poll both sensors already implemented?

**Comment by ba58smith** [comment]
I don't think any of the SigkSens sensors can be used like that (more than one of them installed). You would have to use two ESP's.
You could do it with https://github.com/SignalK/SensESP.
